### ISSUE TITLE
Implement Stacks RFC0004: Stacks based on Ubuntu 2022.04: Jammy Jellyfish

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/stacks#133]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/stacks/0004-jammy-jellyfish.md)

## Summary

A set of stacks based on the Ubuntu 2022.04 LTS (Jammy Jellyfish) release base image should be developed, released, and maintained by the Stacks subteam. Like the existing Bionic stacks, these new stacks should come in "full", "base", and "tiny" variants with similar, if not identical, sets of packages pre-installed.

## Implementation

After the [final release](https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906) date on April 21, 2022, we can release our official stack versions.

### Repositories

The Stacks subteam will create 3 new repos for Jammy:

* `jammy-base-stack`
* `jammy-full-stack`
* `jammy-tiny-stack`

Each of these repos will contain the configuration for its variant of the stack as well as the releases and their related artifacts.

## Sub-Issues

* [x] https://github.com/paketo-buildpacks/jammy-full-stack/issues/1
* [x] https://github.com/paketo-buildpacks/jammy-base-stack/issues/1
* [x] https://github.com/paketo-buildpacks/jammy-tiny-stack/issues/1

**Comment by fg-j** [comment]
Sub-issues:
- https://github.com/paketo-buildpacks/jammy-full-stack/issues/1
- https://github.com/paketo-buildpacks/jammy-base-stack/issues/1
- https://github.com/paketo-buildpacks/jammy-tiny-stack/issues/1

**Comment by fg-j** [comment]
More sub-issues:
- https://github.com/paketo-buildpacks/stack-usns/issues/600
- https://github.com/paketo-buildpacks/stacks/issues/138

**Comment by robdimsdale** [comment]
This is complete (and the remaining sub-issue isn't a blocker for the new stacks architecture). Closing.
